#!/usr/bin/env python3
"""Auto-start VERITY as a SILENT background harness, tied to YOUR main agent.

The goal (DJ): no bulky UI, nothing to remember — VERITY just *runs in the background* and your
main agent (Claude Code / Cursor / Codex / a shell) inherits it, the way switching to a better
model "just works". This wires a tiny, non-blocking, idempotent startup hook into the agent of
your choice. On every session it: (1) quietly git-syncs the repo so you're always current, and
(2) starts the OpenAI-compatible proxy floor (`verity.server` on :11500) if it isn't already up —
so any agent you point at OPENAI_BASE_URL=http://127.0.0.1:11500/v1 transparently gets failover +
the discipline gates.

IMPORTANT (learned 2026-06-15): an ANTHROPIC-format agent (Claude Code / Desktop) talks directly to
api.anthropic.com and CANNOT route through the OpenAI-compatible :11500 proxy — so the proxy alone
never gates its reasoning (`verity proof` stays empty; negative-claim/rule-6 lapses slip through).
For those agents, `--claude-code` ALSO installs a second SessionStart hook that injects VERITY's
core gates as standing CONTEXT every session — that is what actually disciplines the agent. (The
proxy still serves as the sovereign-failover floor + gates anything explicitly run via `verity
solve/ask` or routed through :11500.)

Usage:
  python3 -m verity autostart --claude-code   # add a Claude Code SessionStart hook
  python3 -m verity autostart --shell         # add a line to your shell profile (~/.zshrc etc.)
  python3 -m verity autostart --print         # just print the startup script + manual steps
"""
from __future__ import annotations

import json
import os
import pathlib
import stat

REPO = str(pathlib.Path(__file__).resolve().parent.parent)
SCRIPT = pathlib.Path(os.path.expanduser("~/.verity-harness/autostart.sh"))
INJECT = pathlib.Path(os.path.expanduser("~/.verity-harness/verity-context-inject.sh"))

_SCRIPT_BODY = f"""#!/usr/bin/env bash
# VERITY silent background harness — idempotent, fast, NON-BLOCKING (never delays your agent).
# Auto-generated by `verity autostart`. Safe to run on every session start.
REPO="{REPO}"
(
  # 1. quiet self-sync (stay current; ignore if offline / not a git checkout)
  [ -d "$REPO/.git" ] && git -C "$REPO" pull -q --rebase --autostash >/dev/null 2>&1
  # 2. start the proxy floor only if it isn't already answering
  if ! curl -s -m 1 http://127.0.0.1:11500/health >/dev/null 2>&1; then
    ( cd "$REPO" && nohup python3 -m verity.server >/dev/null 2>&1 & )
  fi
) >/dev/null 2>&1 &
exit 0
"""

# Context-injection for ANTHROPIC-FORMAT agents (Claude Code/Desktop). They talk straight to
# api.anthropic.com and CANNOT route through the OpenAI-compatible :11500 proxy — so the proxy
# alone can't gate their reasoning (verity proof stays empty). This emits VERITY's core gates as
# SessionStart context so the agent applies them manually every session. (DJ, 2026-06-15.)
_INJECT_BODY = f"""#!/usr/bin/env bash
# VERITY gate-injection — auto-generated by `verity autostart`. Prints VERITY's core discipline so
# an Anthropic-format agent (Claude Code) that bypasses the :11500 proxy still runs the gates.
cat <<'GATES'
[VERITY HARNESS — discipline gates ACTIVE this session]
The :11500 failover floor is up, but YOUR reasoning is NOT auto-routed through it (Anthropic-format
agents talk direct to the API) — so apply these gates MANUALLY, every task. Not optional:
 • RULE 0 — PRE-FLIGHT: before executing a goal, search the CURRENT best approach (may supersede
   training). FIND the answer, don't RECALL it.
 • RULE 6 — SEARCH-BEFORE-CONCLUDING (BLOCKER): never assert a NEGATIVE ("there's no X", "not
   possible", "doesn't exist", "unsolvable", "only way is Y") until you've SEARCHED where solutions
   live (the platform's own API, GitHub, Reddit, X, YouTube, StackOverflow). Someone likely solved it.
 • VERIFY (Borg): adversarially confirm each action actually worked; >=2 backends; no "done" on a vibe.
 • REUSE-FIRST: check installed tools + existing OSS BEFORE building.
 • CALIBRATE: label conclusions VERIFIED vs GUESS.
 • Multi-step / uncertain / stuck:  python3 -m verity solve "<goal>"  (fires the gates + logs the ledger).
GATES
curl -s -m 1 http://127.0.0.1:11500/health >/dev/null 2>&1 || ( cd "{REPO}" && nohup python3 -m verity.server >/dev/null 2>&1 & )
exit 0
"""


def write_script() -> pathlib.Path:
    SCRIPT.parent.mkdir(parents=True, exist_ok=True)
    SCRIPT.write_text(_SCRIPT_BODY)
    SCRIPT.chmod(SCRIPT.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP)
    return SCRIPT


def write_inject_script() -> pathlib.Path:
    INJECT.parent.mkdir(parents=True, exist_ok=True)
    INJECT.write_text(_INJECT_BODY)
    INJECT.chmod(INJECT.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP)
    return INJECT


def wire_claude_code() -> str:
    """Add a SessionStart hook to ~/.claude/settings.json (idempotent, preserves everything)."""
    write_script()
    write_inject_script()
    cfg = pathlib.Path(os.path.expanduser("~/.claude/settings.json"))
    data = {}
    if cfg.exists():
        try:
            data = json.loads(cfg.read_text())
        except ValueError:
            return f"[refused] {cfg} is not valid JSON — fix it first, then re-run."
    hooks = data.setdefault("hooks", {})
    changed = []
    # SessionStart → sync + start the proxy floor (silent).
    starts = hooks.setdefault("SessionStart", [])
    if str(SCRIPT) not in json.dumps(starts):
        starts.append({"hooks": [{"type": "command", "command": f"bash {SCRIPT}"}]})
        changed.append("SessionStart→start")
    # SessionStart → inject the discipline gates as CONTEXT (Claude Code bypasses the proxy, so the
    # gates can't auto-fire on its reasoning; this is what actually disciplines an Anthropic agent).
    if str(INJECT) not in json.dumps(starts):
        starts.append({"hooks": [{"type": "command", "command": f"bash {INJECT}", "timeout": 5}]})
        changed.append("SessionStart→inject-gates")
    # SessionEnd → STOP the proxy so it closes when you exit your agent (no lingering RAM).
    stop_cmd = f"python3 -m verity stop"
    ends = hooks.setdefault("SessionEnd", [])
    if "verity stop" not in json.dumps(ends):
        ends.append({"hooks": [{"type": "command", "command": f"cd {REPO} && {stop_cmd}"}]})
        changed.append("SessionEnd→stop")
    if not changed:
        return "[already wired] Claude Code SessionStart→start + SessionEnd→stop."
    cfg.write_text(json.dumps(data, indent=2))
    return (f"[wired] Claude Code: {', '.join(changed)}.\nVERITY now starts silently on session "
            "start and STOPS on session end — it closes when you do, no lingering process. "
            "(Safety net: the proxy also self-shuts-down after idle.)")


def wire_shell() -> str:
    write_script()
    prof = next((pathlib.Path(os.path.expanduser(p)) for p in ("~/.zshrc", "~/.bashrc", "~/.profile")
                 if pathlib.Path(os.path.expanduser(p)).exists()),
                pathlib.Path(os.path.expanduser("~/.zshrc")))
    line = f"[ -f {SCRIPT} ] && bash {SCRIPT}   # VERITY background harness"
    existing = prof.read_text() if prof.exists() else ""
    if str(SCRIPT) in existing:
        return f"[already wired] {prof}"
    with open(prof, "a") as f:
        f.write(f"\n{line}\n")
    return f"[wired] {prof} — new shells start the VERITY harness silently."


def main(target: str) -> None:
    if target == "--claude-code":
        print(wire_claude_code())
    elif target == "--shell":
        print(wire_shell())
    else:
        write_script()
        print("VERITY background-harness startup script written to:\n  " + str(SCRIPT) + "\n")
        print("Wire it into your agent (pick one):")
        print("  • Claude Code:  python3 -m verity autostart --claude-code")
        print("  • Any shell:    python3 -m verity autostart --shell")
        print("  • Manual:       run `bash " + str(SCRIPT) + "` from your agent's startup hook.")
        print("\nThen point your agent at the proxy to inherit failover + gates:")
        print("  export OPENAI_BASE_URL=http://127.0.0.1:11500/v1")


if __name__ == "__main__":
    import sys
    main(sys.argv[1] if len(sys.argv) > 1 else "--print")
