#!/usr/bin/env python3
"""Auto-start VERITY as a SILENT background harness, tied to YOUR main agent.

The goal (DJ): no bulky UI, nothing to remember — VERITY just *runs in the background* and your
main agent (Claude Code / Cursor / Codex / a shell) inherits it, the way switching to a better
model "just works". This wires a tiny, non-blocking, idempotent startup hook into the agent of
your choice. On every session it: (1) quietly git-syncs the repo so you're always current, and
(2) starts the OpenAI-compatible proxy floor (`verity.server` on :11500) if it isn't already up —
so any agent you point at OPENAI_BASE_URL=http://127.0.0.1:11500/v1 transparently gets failover +
the discipline gates.

Usage:
  python3 -m verity autostart --claude-code   # add a Claude Code SessionStart hook
  python3 -m verity autostart --shell         # add a line to your shell profile (~/.zshrc etc.)
  python3 -m verity autostart --print         # just print the startup script + manual steps
"""
from __future__ import annotations

import json
import os
import pathlib
import stat

REPO = str(pathlib.Path(__file__).resolve().parent.parent)
SCRIPT = pathlib.Path(os.path.expanduser("~/.verity-harness/autostart.sh"))

_SCRIPT_BODY = f"""#!/usr/bin/env bash
# VERITY silent background harness — idempotent, fast, NON-BLOCKING (never delays your agent).
# Auto-generated by `verity autostart`. Safe to run on every session start.
REPO="{REPO}"
(
  # 1. quiet self-sync (stay current; ignore if offline / not a git checkout)
  [ -d "$REPO/.git" ] && git -C "$REPO" pull -q --rebase --autostash >/dev/null 2>&1
  # 2. start the proxy floor only if it isn't already answering
  if ! curl -s -m 1 http://127.0.0.1:11500/health >/dev/null 2>&1; then
    ( cd "$REPO" && nohup python3 -m verity.server >/dev/null 2>&1 & )
  fi
) >/dev/null 2>&1 &
exit 0
"""


def write_script() -> pathlib.Path:
    SCRIPT.parent.mkdir(parents=True, exist_ok=True)
    SCRIPT.write_text(_SCRIPT_BODY)
    SCRIPT.chmod(SCRIPT.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP)
    return SCRIPT


def wire_claude_code() -> str:
    """Add a SessionStart hook to ~/.claude/settings.json (idempotent, preserves everything)."""
    write_script()
    cfg = pathlib.Path(os.path.expanduser("~/.claude/settings.json"))
    data = {}
    if cfg.exists():
        try:
            data = json.loads(cfg.read_text())
        except ValueError:
            return f"[refused] {cfg} is not valid JSON — fix it first, then re-run."
    cmd = f"bash {SCRIPT}"
    hooks = data.setdefault("hooks", {})
    sessions = hooks.setdefault("SessionStart", [])
    # idempotent: skip if our command is already wired anywhere in SessionStart
    blob = json.dumps(sessions)
    if str(SCRIPT) in blob:
        return f"[already wired] Claude Code SessionStart → {SCRIPT}"
    sessions.append({"hooks": [{"type": "command", "command": cmd}]})
    cfg.write_text(json.dumps(data, indent=2))
    return (f"[wired] Claude Code SessionStart now runs {SCRIPT} on every session.\n"
            "VERITY syncs + starts its proxy silently in the background from now on.")


def wire_shell() -> str:
    write_script()
    prof = next((pathlib.Path(os.path.expanduser(p)) for p in ("~/.zshrc", "~/.bashrc", "~/.profile")
                 if pathlib.Path(os.path.expanduser(p)).exists()),
                pathlib.Path(os.path.expanduser("~/.zshrc")))
    line = f"[ -f {SCRIPT} ] && bash {SCRIPT}   # VERITY background harness"
    existing = prof.read_text() if prof.exists() else ""
    if str(SCRIPT) in existing:
        return f"[already wired] {prof}"
    with open(prof, "a") as f:
        f.write(f"\n{line}\n")
    return f"[wired] {prof} — new shells start the VERITY harness silently."


def main(target: str) -> None:
    if target == "--claude-code":
        print(wire_claude_code())
    elif target == "--shell":
        print(wire_shell())
    else:
        write_script()
        print("VERITY background-harness startup script written to:\n  " + str(SCRIPT) + "\n")
        print("Wire it into your agent (pick one):")
        print("  • Claude Code:  python3 -m verity autostart --claude-code")
        print("  • Any shell:    python3 -m verity autostart --shell")
        print("  • Manual:       run `bash " + str(SCRIPT) + "` from your agent's startup hook.")
        print("\nThen point your agent at the proxy to inherit failover + gates:")
        print("  export OPENAI_BASE_URL=http://127.0.0.1:11500/v1")


if __name__ == "__main__":
    import sys
    main(sys.argv[1] if len(sys.argv) > 1 else "--print")
